package Admin;

import java.io.File;
import java.io.FileInputStream;
import java.util.Vector;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import voter_reg_sys.CaptureForm;
import voter_reg_sys.EnrollmentForm;
import voter_reg_sys.SnapShot;
import voter_reg_sys.Variables;

/* To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author OLA
 */
public class Student extends javax.swing.JFrame {

    byte[] image = null;
    byte print[] = null;
    byte print2[] = null;
    FormatDate fdate;
    DbConnect dbcon = new DbConnect();
    Variables var = new Variables();
    Vector<Integer> student_id = new Vector<Integer>();
    int h_id;

    public Student() {
        var.setFing(0);
        initComponents();
        fetch();
        fdate = new FormatDate();
        jTextField6.setText(getId());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        jTextField5 = new javax.swing.JTextField();
        jButton6 = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jComboBox1 = new javax.swing.JComboBox();
        jLabel10 = new javax.swing.JLabel();
        jComboBox3 = new javax.swing.JComboBox();
        jLabel11 = new javax.swing.JLabel();
        jTextField6 = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jButton7 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jButton9 = new javax.swing.JButton();
        jLabel24 = new javax.swing.JLabel();
        jComboBox4 = new javax.swing.JComboBox();
        jLabel9 = new javax.swing.JLabel();

        jLabel2.setText("jLabel2");

        jButton1.setBackground(new java.awt.Color(102, 102, 0));
        jButton1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton1.setText("ADD");

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(153, 0, 255));
        jLabel1.setText("STUDENT'S REGISRATION");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 0, 250, 30));

        jLabel3.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        jLabel3.setText("Name:");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 40, 90, 39));

        jLabel4.setFont(new java.awt.Font("Trebuchet MS", 0, 14)); // NOI18N
        jLabel4.setText("Sex:");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 120, 90, 39));

        jLabel5.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        jLabel5.setText("Matric No:");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 80, 90, 39));

        jLabel7.setFont(new java.awt.Font("Trebuchet MS", 0, 14)); // NOI18N
        jLabel7.setText("Mobile No:");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 170, 90, 39));

        jTextField1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        jTextField1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextField1KeyReleased(evt);
            }
        });
        jPanel1.add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 40, 320, 33));

        jTextField3.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        jPanel1.add(jTextField3, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 90, 320, 33));

        jTextField5.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        jTextField5.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextField5KeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextField5KeyTyped(evt);
            }
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextField5KeyPressed(evt);
            }
        });
        jPanel1.add(jTextField5, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 180, 320, 33));

        jButton6.setFont(new java.awt.Font("Trebuchet MS", 0, 14)); // NOI18N
        jButton6.setText("Save");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton6, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 320, 380, 40));

        jLabel8.setBackground(new java.awt.Color(102, 0, 102));
        jLabel8.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        jLabel8.setText("List of Students");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 370, 180, -1));

        jPanel2.setBackground(new java.awt.Color(153, 0, 204));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        jPanel2.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 700, 250));

        jButton2.setFont(new java.awt.Font("Trebuchet MS", 0, 14)); // NOI18N
        jButton2.setText("Delete");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 260, 100, 30));

        jButton3.setFont(new java.awt.Font("Trebuchet MS", 0, 14)); // NOI18N
        jButton3.setText("Update");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 260, 110, 30));

        jButton4.setFont(new java.awt.Font("Trebuchet MS", 0, 14)); // NOI18N
        jButton4.setText("Close");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 260, 90, 30));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 390, 710, 300));

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Gender", "Male", "Female" }));
        jPanel1.add(jComboBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 130, 320, 40));

        jLabel10.setFont(new java.awt.Font("Trebuchet MS", 0, 14)); // NOI18N
        jLabel10.setText("Level:");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 220, 90, 39));

        jComboBox3.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "--Select Level--", "ND 1", "ND 2", "HND 1", "HND 2" }));
        jPanel1.add(jComboBox3, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 220, 110, 40));

        jLabel11.setText("Examination ID:");
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 280, 90, 40));

        jTextField6.setEditable(false);
        jTextField6.setBackground(new java.awt.Color(255, 255, 225));
        jPanel1.add(jTextField6, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 280, 280, 30));

        jLabel12.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel1.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 270, 420, 50));

        jLabel17.setBackground(new java.awt.Color(255, 255, 255));
        jLabel17.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/okprint.jpg"))); // NOI18N
        jLabel17.setText("C:/Users/Oginni/Documents/NetBeansProjects/Voter_Reg_Sys/src/images/thumb.jpg");
        jLabel17.setToolTipText("");
        jLabel17.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(102, 102, 102)));
        jLabel17.setOpaque(true);
        jLabel17.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel17MouseClicked(evt);
            }
        });
        jPanel1.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 240, 100, -1));

        jLabel22.setBackground(new java.awt.Color(255, 255, 255));
        jLabel22.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/okprint.jpg"))); // NOI18N
        jLabel22.setText("C:/Users/Oginni/Documents/NetBeansProjects/Voter_Reg_Sys/src/images/index.jpg");
        jLabel22.setToolTipText("");
        jLabel22.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(102, 102, 102)));
        jLabel22.setOpaque(true);
        jLabel22.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel22MouseClicked(evt);
            }
        });
        jPanel1.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 240, 100, 100));

        jButton7.setText("Index Print");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton7, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 350, -1, -1));

        jButton5.setText("Thumb Print");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 350, -1, -1));

        jButton8.setText("Upload Pix");
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton8, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 200, -1, -1));

        jButton9.setText("Preview");
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton9, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 200, -1, -1));

        jLabel24.setBorder(new javax.swing.border.MatteBorder(null));
        jLabel24.setPreferredSize(new java.awt.Dimension(120, 482));
        jPanel1.add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 30, 150, 160));

        jComboBox4.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "--Select Department--", "Computer Technology", "Food Technology", "Science Laboratory Technolgy", "Polymer", "Textile" }));
        jPanel1.add(jComboBox4, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 220, 200, 40));

        jLabel9.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(4, 30, 450, 340));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        update();
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // TODO add your handling code here:
        if (jButton6.getText().equalsIgnoreCase("Update")) {
            updateData();
            return;
        }
        if (formValidate() == 1) {
            JOptionPane.showMessageDialog(rootPane, "Please supply all required fields");
            return;
        }
        save();
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        delete();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jTable1MouseClicked

    private void jTextField5KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField5KeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField5KeyTyped

    private void jTextField5KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField5KeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField5KeyPressed

    private void jTextField1KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField1KeyReleased
        //   Object ch = evt.getKeyChar();
        //  dbcon.text(jTextField1, ch);
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1KeyReleased

    private void jTextField5KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField5KeyReleased

//        Object ch = evt.getKeyChar();
//        dbcon.num(jTextField5, ch);
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField5KeyReleased

    private void jLabel17MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel17MouseClicked
        jButton4ActionPerformed(null);
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel17MouseClicked

    private void jLabel22MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel22MouseClicked
        jButton7ActionPerformed(null);
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel22MouseClicked

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        //        CaptureForm.log.setText("");
        //        CaptureForm.picture.setIcon(null);
        //        var.setVoterID("");
        //        VerificationForm f = new VerificationForm(new javax.swing.JFrame());
        //        f.whr=3;
        //        f.setVisible(true);
        try {
            var.setFing(2);
            var.setVoterID("");
            EnrollmentForm form = new EnrollmentForm(new javax.swing.JFrame());
            CaptureForm.log.setText("");
            CaptureForm.picture.setIcon(null);
            form.setVisible(true);
        } catch (Exception | ExceptionInInitializerError e) {
            JOptionPane.showMessageDialog(rootPane, "Digital Persona Thumb Print Scanner\nNot Detected ");
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        try {
            var.setFing(1);
            var.setVoterID("");
            EnrollmentForm form = new EnrollmentForm(new javax.swing.JFrame());
            CaptureForm.log.setText("");
            CaptureForm.picture.setIcon(null);
            form.setVisible(true);
        } catch (Exception | ExceptionInInitializerError e) {
            JOptionPane.showMessageDialog(rootPane, "Digital Persona Thumb Print Scanner\nNot Detected ");
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        var.setPixPath("");
        new SnapShot();
        //

        //    System.out.println(" new pix "+var.getPixPath());
    }//GEN-LAST:event_jButton8ActionPerformed

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
        System.out.println(" pat  " + var.getPixPath());
        getpicture(var.getPixPath());

        // TODO add your handling code here:
    }//GEN-LAST:event_jButton9ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Student.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Student.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Student.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Student.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Student().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JComboBox jComboBox1;
    private javax.swing.JComboBox jComboBox3;
    private javax.swing.JComboBox jComboBox4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel22;
    public javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField6;
    // End of variables declaration//GEN-END:variables

    private void save() {
        String name = jTextField1.getText();
        String matricno = jTextField3.getText();
        String sex = jComboBox1.getSelectedItem().toString();
        String mobile = jTextField5.getText();
        String regid = jTextField6.getText();
        String level = jComboBox3.getSelectedItem().toString();
        String dept = jComboBox4.getSelectedItem().toString();

        try {
            String query = "INSERT INTO `students` (`Name`, `MatricNumber`, `Sex`, `Phone`, `Year`,`reg_id`, `thumb_finger`, `pix`, `index_finger`,department) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?);";
            dbcon.ps = dbcon.con.prepareStatement(query);
            dbcon.ps.setString(1, name);
            dbcon.ps.setString(2, matricno);
            dbcon.ps.setString(3, sex);
            dbcon.ps.setString(4, mobile);
            dbcon.ps.setString(5, level);
            dbcon.ps.setString(6, regid);
            dbcon.ps.setBytes(7, print);//finger print stuff
            dbcon.ps.setString(8, var.getPixPath());
            dbcon.ps.setBytes(9, print2);
            dbcon.ps.setString(10, dept);

            if (dbcon.ps.executeUpdate() == 1) {
                JOptionPane.showMessageDialog(rootPane, "Information Saved Successfully");
                fetch();
                clear();
            } else {
                JOptionPane.showMessageDialog(rootPane, "An Error Occur, Your information is not save");
            }

        } catch (Exception e) {
            JOptionPane.showMessageDialog(rootPane, "An Error Occur, Your information is not save");
            e.printStackTrace();
        }
    }

    private void fetch() {
        int j = 0;
        DefaultTableModel model = new DefaultTableModel();
        student_id = new Vector<Integer>();
        model.addColumn("S/N");
        model.addColumn("Exam ID");
        model.addColumn("NAME");
        model.addColumn("MATRIC NO");
        model.addColumn("SEX");
        model.addColumn("PHONE NO");
        model.addColumn("DEPT");
        model.addColumn("LEVEL");
        model.addColumn("STATUS");

        jButton6.setText("Save");
        jLabel22.setVisible(true);
        jLabel24.setVisible(true);
        jButton7.setVisible(true);
        jLabel17.setVisible(true);
        jButton5.setVisible(true);
        jButton8.setVisible(true);
        jButton9.setVisible(true);
        getId();
//=+
        try {
            String query = "select SerialNumber,`Name`, `MatricNumber`, `Sex`, `Phone`, `Year`,`department`,status,reg_id from students ";
            int id;
            String name;
            String matricno;
            String sex;
            String mobile;
            String level;
            String status;
            String regid;
            String dept;
            dbcon.rs = dbcon.st.executeQuery(query);
            while (dbcon.rs.next()) {
                id = dbcon.rs.getInt(1);
                name = dbcon.rs.getString(2);
                matricno = dbcon.rs.getString(3);
                sex = dbcon.rs.getString(4);
                mobile = dbcon.rs.getString(5);
                level = dbcon.rs.getString(6);
                dept = dbcon.rs.getString(7);
                status = dbcon.rs.getString(8);
                regid = dbcon.rs.getString(9);
                String[] object = new String[]{++j + "", regid, name, matricno, sex, mobile, dept, level, status};
                student_id.addElement(id);
                model.addRow(object);
            }
            jTable1.setModel(model);
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(rootPane, "An Error Occur while fetching information from database");
            ex.printStackTrace();
        }
    }

    private void delete() {
        int i = jTable1.getSelectedRow();
        if (i < 0) {
            JOptionPane.showMessageDialog(rootPane, "Please select a feild to be deleted");
            return;
        }
        int id = student_id.elementAt(i);
        try {
            String query = "delete from students where SerialNumber=" + id;
            dbcon.ps = dbcon.con.prepareStatement(query);
            if (dbcon.ps.executeUpdate() == 1) {
                JOptionPane.showMessageDialog(rootPane, "Information Deleted Successfully");
                fetch();
                clear();
            } else {
                JOptionPane.showMessageDialog(rootPane, "An Error Occur, Your information is affected");
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
    }

    private void update() {


        int i = jTable1.getSelectedRow();
        h_id = student_id.elementAt(i);
        String regid = jTable1.getValueAt(i, 1).toString();
        String name = jTable1.getValueAt(i, 2).toString();
        String matricno = jTable1.getValueAt(i, 3).toString();
        String sex = jTable1.getValueAt(i, 4).toString();
        String mobile = jTable1.getValueAt(i, 5).toString();
        String level = jTable1.getValueAt(i, 7).toString();
        String dept = jTable1.getValueAt(i, 6).toString();

        jTextField1.setText(name);
        jTextField3.setText(matricno);
        jTextField5.setText(mobile);
        jTextField6.setText(regid);
        jComboBox1.setSelectedItem(sex);
        jComboBox3.setSelectedItem(level);
        jComboBox4.setSelectedItem(dept);
        jButton6.setText("Update");
        jLabel22.setVisible(false);
        jLabel24.setVisible(false);
        jButton7.setVisible(false);
        jLabel17.setVisible(false);
        jButton5.setVisible(false);
        jButton8.setVisible(false);
        jButton9.setVisible(false);

        if (i < 0) {
            JOptionPane.showMessageDialog(rootPane, "Please select a feild to be update");
            return;
        }
    }

    private void updateData() {
        String name = jTextField1.getText();
        String matricno = jTextField3.getText();
        String sex = jComboBox1.getSelectedItem().toString();
        String mobile = jTextField5.getText();
        String level = jComboBox3.getSelectedItem().toString();
        String dept = jComboBox4.getSelectedItem().toString();

        int id = h_id;
        try {
            String query = "update students set `Name`=?, `MatricNumber`=?, `Sex`=?, `Phone`=?, `Year`=?, `department`=? where SerialNumber=" + id;
            //UPDATE `hall` SET `description` = 'big enough' WHERE `id` =2;
            dbcon.ps = dbcon.con.prepareStatement(query);
            dbcon.ps = dbcon.con.prepareStatement(query);
            dbcon.ps.setString(1, name);
            dbcon.ps.setString(2, matricno);
            dbcon.ps.setString(3, sex);
            dbcon.ps.setString(4, mobile);
            dbcon.ps.setString(5, level);
            dbcon.ps.setString(6, dept);
            if (dbcon.ps.executeUpdate() == 1) {
                JOptionPane.showMessageDialog(rootPane, "Information Updated Successfully");
                fetch();
                clear();
            } else {
                JOptionPane.showMessageDialog(rootPane, "An Error Occur, Your information is not affected");
            }

        } catch (Exception e) {
            JOptionPane.showMessageDialog(rootPane, "An Error Occur, Your information is not affected");
            e.printStackTrace();
        }
    }

    private void getpicture(String path) {
        try {
            if (path.length() > 30000) {
                JOptionPane.showMessageDialog(rootPane, "picture size too large");
                return;
            }
            jLabel24.setIcon(new javax.swing.ImageIcon(path)); // NOI18N
            jLabel24.setBorder(javax.swing.BorderFactory.createEtchedBorder());
            // jPanel1.add(jLabel24);
            jLabel24.setBounds(530, 140, 190, 170);

            this.repaint();
        } catch (Exception e) {
            e.printStackTrace();
            System.out.println("picture " + e);
        }
    }

    private void clear() {
        jTextField6.setText(getId());
        var.setPixPath("");
        getpicture(var.getPixPath());
        jTextField1.setText("");
        jTextField3.setText("");
        jComboBox1.setSelectedIndex(0);
        jComboBox3.setSelectedIndex(0);
        jTextField5.setText("");
        jButton6.setText("save");
    }

    String getId() {
        String id = "";
        String b = "ABCDEFGHIJKLMNOPQRSTUVWXYZ1234567890";
        char c[] = b.toCharArray();
        for (int i = 0; i < 25; i++) {
            id += c[(int) (Math.random() * 36)];
        }
        try {
            dbcon.rs = dbcon.st.executeQuery("select * from students where reg_id='" + id + "'");
            if (dbcon.rs.next()) {
                getId();
            }
        } catch (Exception g) {
            System.out.println("" + g);
        }
        return id;
    }

    private int formValidate() {
        print = EnrollmentForm.print;
        print2 = EnrollmentForm.print2;

        try {
            if (var.getPixPath().isEmpty()) {
                JOptionPane.showMessageDialog(rootPane, "Upload Pix for User please");
                return 1;
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(rootPane, "Image not set!!!");
            return 1;
        }
        if (var.getFing() < 1) {
            JOptionPane.showMessageDialog(rootPane, "Thumb finger print reqiured");
            return 1;
        }
        if (var.getFing() < 2) {
            JOptionPane.showMessageDialog(rootPane, "Index finger print reqiured");
            return 1;
        }

        try {
            if (print != null) {
                File f = new File(jLabel17.getText());
                FileInputStream in = new FileInputStream(f);
                image = new byte[(int) f.length()];
                in.read(image);
                in.read(print);
            } else {
                JOptionPane.showMessageDialog(rootPane, "Thumb finger print not set");
                return 1;
            }
            if (print2 != null) {
                File f = new File(jLabel22.getText());
                FileInputStream in = new FileInputStream(f);
                image = new byte[(int) f.length()];
                in.read(image);
                in.read(print2);
            } else {
                JOptionPane.showMessageDialog(rootPane, "Index finger print not set");
                return 1;
            }
        } catch (Exception e) {
            e.printStackTrace();
        }



        if (jTextField1.getText().isEmpty()) {
            jTextField1.requestFocus();
            return 1;
        }
        if (jTextField3.getText().isEmpty()) {
            jTextField3.requestFocus();
            return 1;
        }
        if (jTextField5.getText().isEmpty()) {
            jTextField5.requestFocus();
            return 1;
        }
        if (jComboBox1.getSelectedIndex() == 0) {
            jComboBox1.requestFocus();
            return 1;
        }
        if (jComboBox3.getSelectedIndex() == 0) {
            jComboBox1.requestFocus();
            return 1;
        }

        return 0;
    }
}
